### ISSUE TITLE
Ngrok Direct link not generated 

### ISSUE THREAD

**Issue by asherzod1** [MrHacker-X/Traper-X#1]
Ngrok Direct link not generated

**Comment by asherzod1** [comment]
i have a solution

**Comment by steamcleanerboi** [comment]
please help me same problem

**Comment by steamcleanerboi** [comment]
> i have a solution

what is it?

**Comment by asherzod1** [comment]
[traperx.txt](https://github.com/MrHacker-X/Traper-X/files/11068597/traperx.txt)
Replace the code in the traperx.sh file with this traperx.txt
